title: Resistors
hero_image: images/banner.png
description: generic-physical-resistors description
version: 4
listed: false
copyedit: false
last_tested: "2022-03-22"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
