title: Understand resistor values
hero_image: images/banner.png
description: Understand how resistors work and how to read values from colour bands. 
version: 4
listed: false
copyedit: false
last_tested: "2022-03-22"
steps:
  - title: Understand resistor values

